# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
#code here
import numpy as np

array_1d = np.arange(12)
array_2d = array_1d.reshape(3, 4)
print("2D array:")
print(array_2d)

array_1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
array_2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

horizontal = np.concatenate((array_1, array_2), axis=1)
print("Horizontal array:")
print(horizontal)

vertical = np.concatenate((array_1, array_2), axis=0)
print("Vertical array:")
print(vertical)

2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Horizontal array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertical array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [ ]:
#code here
def classify_email(emails):
    important = ["urgent", "important", "action required"]
    promotions = ["sale", "deal", "discount", "offer"]
    spam = ["lottery", "prize", "won"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        email_lower = email.lower()
        if any(keyword in email_lower for keyword in important):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promotions):
            promotions_emails.append(email)
        elif any(keyword in email_lower for keyword in spam):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails


emails = [
    "URGENT: Action Required - Verify Your Account",
    "Exclusive Sale - 70% Off!",
    "You've won a Lottery Prize!",
    "Important Update: Your Subscription Renewal",
    "Limited Time Deal - Get 10-15% Off Today",
    "Important: Meeting Reminder for Tomorrow",
    "Last Chance to Save Big - End of Season Sale!",
    "You've Won a Free Vacation!",
    "Action Required: Update Your Payment Method",
    "Exclusive Offer: Buy One Get One Free!",
    "Congratulations! You've Won a Cash Prize!"
]

print("List of emails:\n",emails)
important, promotions, spam = classify_email(emails)

print("Important Emails:")
for email in important:
    print(".", email)

print("Promotion Emails:")
for email in promotions:
    print(".", email)

print("Spam Emails:")
for email in spam:
    print(".", email)


List of emails:
 ['URGENT: Action Required - Verify Your Account', 'Exclusive Sale - 70% Off!', "You've won a Lottery Prize!", 'Important Update: Your Subscription Renewal', 'Limited Time Deal - Get 10-15% Off Today', 'Important: Meeting Reminder for Tomorrow', 'Last Chance to Save Big - End of Season Sale!', "You've Won a Free Vacation!", 'Action Required: Update Your Payment Method', 'Exclusive Offer: Buy One Get One Free!', "Congratulations! You've Won a Cash Prize!"]

Important Emails:
. URGENT: Action Required - Verify Your Account
. Important Update: Your Subscription Renewal
. Important: Meeting Reminder for Tomorrow
. Action Required: Update Your Payment Method

Promotion Emails:
. Exclusive Sale - 70% Off!
. Limited Time Deal - Get 10-15% Off Today
. Last Chance to Save Big - End of Season Sale!
. Exclusive Offer: Buy One Get One Free!

Spam Emails:
. You've won a Lottery Prize!
. You've Won a Free Vacation!
. Congratulations! You've Won a Cash Prize!


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [ ]:
#code here
def translate_word(word):
    if word in english_spanish_dict:
        return english_spanish_dict[word]
    else:
        return "Translation not available."

english_spanish_dict = {
    "hello": "hola",
    "bye": "adiós",
    "cat": "gato",
    "dog": "perro",
    "house": "casa",
    "good":"ueno"
}

while True:
    word = input("Enter an English word (or type 'exit' to quit): ").lower()
    if word == "exit":
        print("Bye!")
        break
    translation = translate_word(word)
    print("Word in Spanish:", translation)


Enter an English word (or type 'exit' to quit): hello
Word in Spanish: hola
Enter an English word (or type 'exit' to quit): cat
Word in Spanish: gato
Enter an English word (or type 'exit' to quit): house
Word in Spanish: casa
Enter an English word (or type 'exit' to quit): exit
Bye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [ ]:
#code here
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")

total_global_sales = df['Global_Sales'].sum()
print("Total Global Sales:", total_global_sales)

print("Game with the Highest Global Sales:")
print(df.loc[df['Global_Sales'].idxmax()])

print("Average Sales for Each Region:")
print(df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean())

print("Top 5 Most Popular Game Genres based on Global Sales:")
print(df.groupby('Genre')['Global_Sales'].sum().nlargest(5))

genre_sales_by_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print("Most Popular Genre in North America:", genre_sales_by_region['NA_Sales'].idxmax())

print("Top 3 Gaming Platforms with the Highest Global Sales:")
print(df.groupby('Platform')['Global_Sales'].sum().nlargest(3))

total_global_sales_per_genre = df.groupby('Genre')['Global_Sales'].sum()
market_share_per_genre = (total_global_sales_per_genre / total_global_sales) * 100
print("Market Share Percentage for Each Genre:")
print(market_share_per_genre)

print("Correlation Coefficient between NA Sales and EU Sales:", df['NA_Sales'].corr(df['EU_Sales']))

print("Last 10 Rows:")
print(df.tail(10))

Total Global Sales: 8920.44
Game with the Highest Global Sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object
Average Sales for Each Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
Top 5 Most Popular Game Genres based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
Most Popular Genre in North America: Action
Top 3 Gaming Platforms with the Highest Global Sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64
Market Share Percentage for Each Genre:
Genre
Action          19.6310